import kNN
#import matplotlib
#group,labels=kNN.createDataSet()
#result=kNN.classify0([0,0],group,labels,3)
#print(result)
#datingDataMat,datingLabels=kNN.file2matrix('datingTestSet.txt')
#print(datingDataMat)
#print(datingLabels[0:20])
#normMat,range,minVals=kNN.autoNorm(datingDataMat)
#print(normMat)
#print(range)
#print(minVals)
#kNN.classifyPerson()
#testVector=kNN.img2vector('digits/testDigits/0_13.txt')
#print(testVector[0,32:63])
kNN.handwritingClassTest()